events {
    worker_connections 1024;
}

http {
    # Define JSON format for easy Python parsing
    log_format hng_json escape=json '{'
        '"source_ip": "$remote_addr", '
        '"timestamp": "$time_iso8601", '
        '"method": "$request_method", '
        '"path": "$request_uri", '
        '"status": "$status", '
        '"response_size": "$body_bytes_sent"'
    '}';

    server {
        listen 80;
        
        # Write logs to the shared volume path
        access_log /var/log/nginx/hng-access.log hng_json;

        location / {
            proxy_pass http://nextcloud:80;
            # Forward real client IP for accurate detection
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
